# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  pipeline:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports:
          - '5432:5432'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      chrome:
        image: browserless/chrome:1.31-chrome-stable
        env:
          PORT: 3333
          CONNECTION_TIMEOUT: 600000
        ports:
          - "3333:3333"
    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      CHROME_URL: http://chrome:3333

    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - name: Build
      run: |
        sudo apt-get -yqq install libpq-dev
        bundle install --jobs 4 --retry 3
        bundle exec rails db:prepare
        yarn install
    - name: Lint
      run: bundle exec standardrb
    - name: Test
      run: bundle exec rspec
